AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

# Added to avoid updating many files
Style/StringLiterals:
  EnforcedStyle: double_quotes